<a href="https://colab.research.google.com/github/Roshaninikhare56/Boston-House-Pricing/blob/main/Naive_bayes_multinomial_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_20newsgroups

news = fetch_20newsgroups()

In [2]:
news.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [3]:
news.target

array([7, 4, 4, ..., 3, 1, 8])

In [4]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [5]:
cats = ['alt.atheism','soc.religion.christian','comp.graphics','sci.med']

news_train = fetch_20newsgroups(subset='train',categories= cats)

In [6]:
news_test = fetch_20newsgroups(subset='test',categories= cats)

In [7]:
print(news_train.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [8]:
news_train['target_names']

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()

In [13]:
X_train_tf = count_vect.fit_transform(news_train.data)

X_train_tf.shape

(2257, 35788)

In [15]:
print(X_train_tf)

  (0, 14887)	1
  (0, 29022)	1
  (0, 8696)	4
  (0, 4017)	2
  (0, 33256)	2
  (0, 21661)	3
  (0, 9031)	3
  (0, 31077)	1
  (0, 9805)	2
  (0, 17366)	1
  (0, 32493)	4
  (0, 16916)	2
  (0, 19780)	2
  (0, 17302)	2
  (0, 23122)	1
  (0, 25663)	1
  (0, 16881)	1
  (0, 16082)	1
  (0, 23915)	1
  (0, 32142)	5
  (0, 33597)	2
  (0, 20253)	1
  (0, 587)	1
  (0, 12051)	1
  (0, 5201)	1
  :	:
  (2256, 13740)	1
  (2256, 14662)	1
  (2256, 20201)	1
  (2256, 12443)	6
  (2256, 30325)	3
  (2256, 4610)	1
  (2256, 33844)	1
  (2256, 17354)	1
  (2256, 26998)	1
  (2256, 20277)	1
  (2256, 20695)	1
  (2256, 20702)	1
  (2256, 9649)	1
  (2256, 9086)	1
  (2256, 26254)	1
  (2256, 17133)	2
  (2256, 4490)	1
  (2256, 13720)	1
  (2256, 5016)	1
  (2256, 9632)	1
  (2256, 11824)	1
  (2256, 29993)	1
  (2256, 1298)	1
  (2256, 2375)	1
  (2256, 3921)	1


In [16]:
# TFID Transformer : weight the word of the classifier, if any words get repeated multiple times in any text then find out how much is the contribution of the
# in the classification.

from sklearn.feature_extraction.text import TfidfTransformer

tfidf_trans = TfidfTransformer()

X_train_tfidf = tfidf_trans.fit_transform(X_train_tf)

X_train_tfidf.shape

(2257, 35788)

In [18]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB().fit(X_train_tfidf, news_train.target)

In [21]:
X_test_tf = count_vect.transform(news_test.data)



In [22]:
X_test_tfidf = tfidf_trans.transform(X_test_tf)
predicted = clf.predict(X_test_tfidf)
predicted

array([2, 2, 3, ..., 2, 2, 1])

In [25]:
from sklearn import metrics

from sklearn.metrics import accuracy_score

print("Accuracy",accuracy_score(news_test.target,predicted))

print(metrics.confusion_matrix(news_test.target,predicted))

Accuracy 0.8348868175765646
[[192   2   6 119]
 [  2 347   4  36]
 [  2  11 322  61]
 [  2   2   1 393]]
